// +build linux

package ibverbs

//#include <infiniband/verbs.h>
import "C"

const (
	IBV_ACCESS_LOCAL_WRITE = C.IBV_ACCESS_LOCAL_WRITE
	IBV_ACCESS_REMOTE_WRITE = C.IBV_ACCESS_REMOTE_WRITE
	IBV_ACCESS_REMOTE_READ = C.IBV_ACCESS_REMOTE_READ
	IBV_ACCESS_REMOTE_ATOMIC = C.IBV_ACCESS_REMOTE_ATOMIC
)
